# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    timeout-minutes: 120
    runs-on: windows-latest

    steps:
      - { name: Check defender, shell: cmd, run: sc query WinDefend }
      - { name: Disable defender, shell: cmd, run: runas /noprofile /user:Administrator sc stop WinDefend }
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Show systeminfo
        shell: cmd
        run: systeminfo
      - name: Build with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: runDebugExecutableNative
      - name: Show systeminfo
        shell: cmd
        run: systeminfo
